run:
  timeout: 5m

linters:
  enable:
    - gosec
    - staticcheck

linters-settings:
  gosec:
    excludes: []
    confidence: low
    severity: medium

issues:
  exclude-dirs:
    - .repos
    - web
  exclude-dirs-use-default: true
